on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  build_artifact:
    if: github.repository == 'Thomas-X/cdktf-aws'
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    env:
      CHECKPOINT_DISABLE: "1"

    steps:
      - uses: actions/checkout@v2
      - name: installing dependencies
        run: |
          yarn install
      - name: compile
        run: |
          chmod +x ./tools/align-version.sh
          chmod +x ./tools/collect-dist.sh
          ./tools/align-version.sh
          yarn build
      - name: create bundle
        run: yarn package
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  release_npm:
    name: Release to NPM registry
    needs: build_artifact
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Release
        run: npx -p publib publib-npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release_nuget:
    name: Release to nuget registry
    needs: build_artifact
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Release
        run: npx -p publib publib-nuget
        env:
          NPM_TOKEN: ${{ secrets.NUGET_API_KEY }}